#!/usr/bin/env python3
"""Register a Seedance 2.5 GIF generated by Doubao Work's built-in tool."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
from typing import Any, Dict, Optional, Sequence

from runtime_profile import default_motion_mode, motion_mode_config, motion_runtime


ROOT = Path(__file__).resolve().parents[1]


def _inside_root(value: str) -> Path:
    path = Path(value).expanduser()
    path = path.resolve() if path.is_absolute() else (ROOT / path).resolve()
    try:
        path.relative_to(ROOT)
    except ValueError as exc:
        raise ValueError(f"path must stay inside the Skill directory: {path}") from exc
    return path


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _inspect_gif(path: Path) -> Dict[str, Any]:
    try:
        from PIL import Image
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("GIF validation requires Pillow") from exc
    with Image.open(path) as image:
        if str(image.format or "").upper() != "GIF":
            raise ValueError("Seedance motion asset must be a real GIF, not a renamed video or image")
        frame_count = int(getattr(image, "n_frames", 1) or 1)
        if frame_count < 2:
            raise ValueError("hero.gif must contain at least two frames")
        width, height = image.size
        durations: list[int] = []
        for index in range(min(frame_count, 240)):
            image.seek(index)
            durations.append(max(0, int(image.info.get("duration", 0) or 0)))
    return {
        "format": "GIF",
        "width": width,
        "height": height,
        "frame_count": frame_count,
        "duration_ms_scanned": sum(durations),
        "animated": True,
    }


def register(
    asset: str,
    *,
    prompt: Optional[str] = None,
    output: Optional[str] = None,
    tool: str = "doubao.video_gen",
    model_id: str = "platform-managed",
    generation_mode: Optional[str] = None,
) -> Dict[str, Any]:
    runtime = motion_runtime()
    resolved_mode = generation_mode or default_motion_mode()
    mode = motion_mode_config(resolved_mode)
    asset_path = _inside_root(asset)
    if not asset_path.is_file():
        raise ValueError(f"motion asset not found: {asset_path}")
    if asset_path.name != "hero.gif":
        raise ValueError("the selected Seedance asset must be named hero.gif")
    from asset_validation import inspect_asset
    inspection = inspect_asset(asset_path, "GIF")
    prompt_path = _inside_root(prompt) if prompt else asset_path.with_name(f"{asset_path.parent.name}.motion-prompt.md")
    if not prompt_path.is_file():
        raise ValueError(f"motion prompt file not found: {prompt_path}")
    output_path = _inside_root(output) if output else asset_path.with_name("hero-motion-generation.json")
    manifest: Dict[str, Any] = {
        "schema": "doubao-feishu-motion-provenance/1",
        "tool": tool,
        "generation_family": str(runtime.get("generation_family") or "seedance-class"),
        "model_id": model_id,
        "generation_model": str(runtime.get("generation_model") or "seedance-2.5"),
        "generation_model_label": str(runtime.get("generation_model_label") or "Seedance 2.5"),
        "generation_model_source": "configured_profile_pending_runtime_observation",
        "generation_mode": resolved_mode,
        "output_format": str(mode.get("output_format") or runtime.get("output_format") or "gif"),
        "asset": str(asset_path),
        "asset_name": asset_path.name,
        "asset_sha256": _sha256(asset_path),
        "inspection": inspection,
        "prompt_file": str(prompt_path),
        "prompt_sha256": _sha256(prompt_path),
        "registered_at": datetime.now(timezone.utc).isoformat(),
        "post_processing": "none",
    }
    output_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return manifest


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Register Doubao Seedance 2.5 direct GIF provenance")
    parser.add_argument("--asset", required=True, help="Seedance-generated hero.gif")
    parser.add_argument("--prompt", help="motion prompt; defaults to sibling *.motion-prompt.md")
    parser.add_argument("--output", help="manifest path; defaults to hero-motion-generation.json")
    parser.add_argument("--tool", default="doubao.video_gen")
    parser.add_argument("--model-id", default="platform-managed")
    parser.add_argument("--generation-mode", default=default_motion_mode())
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    try:
        args = parse_args(argv)
        manifest = register(
            args.asset,
            prompt=args.prompt,
            output=args.output,
            tool=args.tool,
            model_id=args.model_id,
            generation_mode=args.generation_mode,
        )
        print(json.dumps({"ok": True, **manifest}, ensure_ascii=False, indent=2))
        return 0
    except (OSError, RuntimeError, ValueError, TypeError) as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
